openapi: 3.0.0
info:
  title: POS-Penjualan
  version: 1.0.0
servers:
  - url: http://localhost:8001/api/
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Auth
  - name: Role
  - name: User
  - name: Rak
  - name: Category
paths:
  /v1/auth/login:
    $ref: "auth.yml#/login"
  /v1/auth/me:
    $ref: "auth.yml#/me"
  /v1/auth/change-profile:
    $ref: "auth.yml#/change-profile"
  /v1/auth/refresh:
    $ref: "auth.yml#/refresh"
  /v1/auth/logout:
    $ref: "auth.yml#/logout"

  /v1/iam/role:
    $ref: "iam/role.yml#/list_and_create"
  /v1/iam/role/{roleId}:
    $ref: "iam/role.yml#/update_and_delete"

  /v1/iam/user:
    $ref: "iam/user.yml#/list_and_create"
  /v1/iam/user/{userId}:
    $ref: "iam/user.yml#/update_and_delete"
  /v1/iam/user/{userId}/change-avatar:
    $ref: "iam/user.yml#/change_avatar"

  /v1/master/rak:
    $ref: "master/rak.yml#/list_and_create"
  /v1/master/rak/{rakId}:
    $ref: "master/rak.yml#/update_and_delete"

  /v1/master/kategori:
    $ref: "master/kategori.yml#/list_and_create"
  /v1/master/kategori/{categoryId}:
    $ref: "master/kategori.yml#/update_and_delete"

  /v1/master/inventaris:
    $ref: "master/inventaris.yml#/list_and_create"
  /v1/master/inventaris/not-empty-stock:
    $ref: "master/inventaris.yml#/not_empty_stock"
  /v1/master/inventaris/{inventarisId}/modify-stock:
    $ref: "master/inventaris.yml#/modify-stock"
  /v1/master/inventaris/{inventarisId}:
    $ref: "master/inventaris.yml#/update_and_delete"
